(*                                                                            *)
(* File generated by the B&R AS 4 control config generator                    *)
(*                                                                            *)
(*     Provider: machineering                                                 *)
(*  Application: iPhysics_2.4.master                                          *)
(* Architecture: Windows 64 Bit                                               *)
(*      Version: 2.4.12706.master                                             *)
(*        Build: 608a88cb4                                                    *)
(*         Date: 2022-08-25, Time: 10:57:22                                   *)
(*                                                                            *)

TYPE
ComTCP_INPUTS_32BIT : STRUCT



		NumSignals	: INT := 32;

        diEmergencyStop : BOOL := 0;
        (* BOOL diEmergencyStop *)
        diEntranceSensor : BOOL := 0;
        (* BOOL diEntranceSensor *)
        aiEntranceSoilLevel : REAL := 0.0;
        (* REAL aiEntranceSoilLevel *)
        diHighPressSensor1 : BOOL := 0;
        (* BOOL diHighPressSensor1 *)
        diHighPressSensor2 : BOOL := 0;
        (* BOOL diHighPressSensor2 *)
        diHighPressSensor3 : BOOL := 0;
        (* BOOL diHighPressSensor3 *)
        diHighPressSensor4 : BOOL := 0;
        (* BOOL diHighPressSensor4 *)
        diHBrushSensor1 : BOOL := 0;
        (* BOOL diHBrushSensor1 *)
        diHBrushSensor2 : BOOL := 0;
        (* BOOL diHBrushSensor2 *)
        diHBrushSensor3 : BOOL := 0;
        (* BOOL diHBrushSensor3 *)
        diHBrushSensor4 : BOOL := 0;
        (* BOOL diHBrushSensor4 *)
        aiVBrushLForceF : REAL := 0.0;
        (* REAL aiVBrushLForceF *)
        aiVBrushLForceS : REAL := 0.0;
        (* REAL aiVBrushLForceS *)
        aiVBrushRForceF : REAL := 0.0;
        (* REAL aiVBrushRForceF *)
        aiVBrushRForceS : REAL := 0.0;
        (* REAL aiVBrushRForceS *)
        diHPolishSensor1 : BOOL := 0;
        (* BOOL diHPolishSensor1 *)
        diHPolishSensor2 : BOOL := 0;
        (* BOOL diHPolishSensor2 *)
        diHPolishSensor3 : BOOL := 0;
        (* BOOL diHPolishSensor3 *)
        diHPolishSensor4 : BOOL := 0;
        (* BOOL diHPolishSensor4 *)
        aiVPolishLForceF : REAL := 0.0;
        (* REAL aiVPolishLForceF *)
        aiVPolishLForceS : REAL := 0.0;
        (* REAL aiVPolishLForceS *)
        aiVPolishRForceF : REAL := 0.0;
        (* REAL aiVPolishRForceF *)
        aiVPolishRForceS : REAL := 0.0;
        (* REAL aiVPolishRForceS *)
        diHDry1Sensor1 : BOOL := 0;
        (* BOOL diHDry1Sensor1 *)
        diHDry1Sensor2 : BOOL := 0;
        (* BOOL diHDry1Sensor2 *)
        diHDry1Sensor3 : BOOL := 0;
        (* BOOL diHDry1Sensor3 *)
        diHDry1Sensor4 : BOOL := 0;
        (* BOOL diHDry1Sensor4 *)
        diHDry2Sensor1 : BOOL := 0;
        (* BOOL diHDry2Sensor1 *)
        diHDry2Sensor2 : BOOL := 0;
        (* BOOL diHDry2Sensor2 *)
        diHDry2Sensor3 : BOOL := 0;
        (* BOOL diHDry2Sensor3 *)
        diHDry2Sensor4 : BOOL := 0;
        (* BOOL diHDry2Sensor4 *)
        aiWaterLevel : REAL := 0.0;
        (* REAL aiWaterLevel *)

	END_STRUCT;

ComTCP_OUTPUTS_32BIT : STRUCT


		NumSignals	: INT := 53;

        doMaintenanceMode : BOOL := 0;
        (* BOOL doMaintenanceMode *)
        aoChemChemValve : REAL := 0.0;
        (* REAL aoChemChemValve *)
        doChemWaterValve : BOOL := 0;
        (* BOOL doChemWaterValve *)
        doChemRefill : BOOL := 0;
        (* BOOL doChemRefill *)
        doHighPressLiftRelay : BOOL := 0;
        (* BOOL doHighPressLiftRelay *)
        doHighPressLowerRelay : BOOL := 0;
        (* BOOL doHighPressLowerRelay *)
        doHighPressValve : BOOL := 0;
        (* BOOL doHighPressValve *)
        doHighPressPumpRelay : BOOL := 0;
        (* BOOL doHighPressPumpRelay *)
        doHBrushLiftRelay : BOOL := 0;
        (* BOOL doHBrushLiftRelay *)
        doHBrushLowerRelay : BOOL := 0;
        (* BOOL doHBrushLowerRelay *)
        doHBrushValve : BOOL := 0;
        (* BOOL doHBrushValve *)
        doHBrushBrushRelay : BOOL := 0;
        (* BOOL doHBrushBrushRelay *)
        doVBrushRelayLClose : BOOL := 0;
        (* BOOL doVBrushRelayLClose *)
        doVBrushRelayLOpen : BOOL := 0;
        (* BOOL doVBrushRelayLOpen *)
        doVBrushRelayRClose : BOOL := 0;
        (* BOOL doVBrushRelayRClose *)
        doVBrushRelayROpen : BOOL := 0;
        (* BOOL doVBrushRelayROpen *)
        aoVBrushLVel : REAL := 0.0;
        (* REAL aoVBrushLVel *)
        aoVBrushRVel : REAL := 0.0;
        (* REAL aoVBrushRVel *)
        doVBrushValve : BOOL := 0;
        (* BOOL doVBrushValve *)
        doVBrushRelayBrush : BOOL := 0;
        (* BOOL doVBrushRelayBrush *)
        doUnderbodyValve : BOOL := 0;
        (* BOOL doUnderbodyValve *)
        doUnderbodyPumpRelay : BOOL := 0;
        (* BOOL doUnderbodyPumpRelay *)
        doHPolishLiftRelay : BOOL := 0;
        (* BOOL doHPolishLiftRelay *)
        doHPolishLowerRelay : BOOL := 0;
        (* BOOL doHPolishLowerRelay *)
        doHPolishBrushRelay : BOOL := 0;
        (* BOOL doHPolishBrushRelay *)
        doVPolishRelayLClose : BOOL := 0;
        (* BOOL doVPolishRelayLClose *)
        doVPolishRelayLOpen : BOOL := 0;
        (* BOOL doVPolishRelayLOpen *)
        doVPolishRelayRClose : BOOL := 0;
        (* BOOL doVPolishRelayRClose *)
        doVPolishRelayROpen : BOOL := 0;
        (* BOOL doVPolishRelayROpen *)
        aoVPolishLVel : REAL := 0.0;
        (* REAL aoVPolishLVel *)
        aoVPolishRVel : REAL := 0.0;
        (* REAL aoVPolishRVel *)
        doVPolishRelayBrush : BOOL := 0;
        (* BOOL doVPolishRelayBrush *)
        doWaxValve : BOOL := 0;
        (* BOOL doWaxValve *)
        doWaxPumpRelay : BOOL := 0;
        (* BOOL doWaxPumpRelay *)
        doWaxRefill : BOOL := 0;
        (* BOOL doWaxRefill *)
        doHDry1LiftRelay : BOOL := 0;
        (* BOOL doHDry1LiftRelay *)
        doHDry1LowerRelay : BOOL := 0;
        (* BOOL doHDry1LowerRelay *)
        doHDry1VentRelay : BOOL := 0;
        (* BOOL doHDry1VentRelay *)
        doHDry1HeaterRelay : BOOL := 0;
        (* BOOL doHDry1HeaterRelay *)
        doVDry1VentRelay : BOOL := 0;
        (* BOOL doVDry1VentRelay *)
        doVDry1HeaterRelay : BOOL := 0;
        (* BOOL doVDry1HeaterRelay *)
        doHDry2LiftRelay : BOOL := 0;
        (* BOOL doHDry2LiftRelay *)
        doHDry2LowerRelay : BOOL := 0;
        (* BOOL doHDry2LowerRelay *)
        doHDry2VentRelay : BOOL := 0;
        (* BOOL doHDry2VentRelay *)
        doHDry2HeaterRelay : BOOL := 0;
        (* BOOL doHDry2HeaterRelay *)
        doConvRelay : BOOL := 0;
        (* BOOL doConvRelay *)
        doWaterValve : BOOL := 0;
        (* BOOL doWaterValve *)
        doTankWaterValve : BOOL := 0;
        (* BOOL doTankWaterValve *)
        doExitGreenLight : BOOL := 0;
        (* BOOL doExitGreenLight *)
        doExitOrangeLight : BOOL := 0;
        (* BOOL doExitOrangeLight *)
        doExitRedLight : BOOL := 0;
        (* BOOL doExitRedLight *)
        doExitLiftDoorRelay : BOOL := 0;
        (* BOOL doExitLiftDoorRelay *)
        doExitLowerDoorRelay : BOOL := 0;
        (* BOOL doExitLowerDoorRelay *)

	END_STRUCT;


END_TYPE
